### ISSUE TITLE
Lecture 4: Image code blocks

### ISSUE THREAD

**Issue by PrometheusUA** [VSydorskyy/iasa_nlp_course#11]
Do you really need these code blocks inside lecture 4?

For example, in Short_Explanation_what_is_nn_Embedding:
```
Image("images/Screenshot from 2023-10-16 12-53-17.png")
```

My thought is that they could have been replaced with a simple image markdown text, like:
```
![](./images/Screenshot%20from%202023-10-16%2012-53-17.png)
```

**Comment by VSydorskyy** [comment]
It is a good point! We will use your construction for the next lectures and courses.

But as for already created lectures - it does not seem to be a bug.

But if you want to fix on long winter evenings - I will definitely review and merge your PR :)
