### ISSUE TITLE
Lecture 4: Empty anchors in homework

### ISSUE THREAD

**Issue by PrometheusUA** [VSydorskyy/iasa_nlp_course#12]
You use #Token_Classification and #Sentence_Classification anchors in the Homework section while not having them inside the notebook. Maybe, it is a "bug" to be fixed.

**Comment by VSydorskyy** [comment]
Seems to work for me. Can you pls double-check?

**Comment by PrometheusUA** [comment]
Yes, everything is OK there. It seems to be a VS Code-specific thing. Anchoring works with plain section names there, not with HTML anchors inserted, so "Validation" and "Home" (as being equal to full section names) work, and others don't.
